[package]
name = "stripe"
version = "0.1."
edition = "2018"

[dependencies]
tokio = { version = "1.0", features = ["macros"] }
lambda_http = { git = "https://github.com/awslabs/aws-lambda-rust-runtime", branch = "master"}
lambda = { git = "https://github.com/awslabs/aws-lambda-rust-runtime", branch = "master"}
serde_json = "1.0"
aws = { path = "../../utils/aws" }