[package]
name = "demon_ddsl"
version = "0.0.1"
authors = ["richardwesthaver <richard.westhaver@gmail.com>"]
edition = "2018"

[dependencies]
duckscript = { version = "^0.5.1" }
duckscriptsdk = { version = "^0.6.8" }
rand = "0.7.3"