[package]
name = "macros"
edition = "2018"
version = "0.0.1"
authors = ['ellis']
include = ["**/*.rs"]

[lib]
path = "lib.rs"
proc-macro = true

[dependencies]
proc-macro2 = "1.0"
quote = "1.0"
syn = { version = "1.0", features = ["full", "visit", "visit-mut", "fold", "extra-traits"] }